# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(230, 240)
        self.LE_Variety = QtWidgets.QLineEdit(Form)
        self.LE_Variety.setGeometry(QtCore.QRect(110, 8, 113, 20))
        self.LE_Variety.setObjectName("LE_Variety")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 8, 91, 21))
        self.label_2.setObjectName("label_2")
        self.LE_Roast = QtWidgets.QLineEdit(Form)
        self.LE_Roast.setGeometry(QtCore.QRect(110, 38, 113, 20))
        self.LE_Roast.setObjectName("LE_Roast")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 38, 101, 21))
        self.label_3.setObjectName("label_3")
        self.LE_Type = QtWidgets.QLineEdit(Form)
        self.LE_Type.setGeometry(QtCore.QRect(110, 68, 113, 20))
        self.LE_Type.setObjectName("LE_Type")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 68, 91, 21))
        self.label_4.setObjectName("label_4")
        self.LE_Taste = QtWidgets.QLineEdit(Form)
        self.LE_Taste.setGeometry(QtCore.QRect(110, 98, 113, 20))
        self.LE_Taste.setObjectName("LE_Taste")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 98, 91, 21))
        self.label_5.setObjectName("label_5")
        self.LE_Price = QtWidgets.QLineEdit(Form)
        self.LE_Price.setGeometry(QtCore.QRect(110, 128, 113, 20))
        self.LE_Price.setObjectName("LE_Price")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 128, 91, 21))
        self.label_6.setObjectName("label_6")
        self.LE_Volume = QtWidgets.QLineEdit(Form)
        self.LE_Volume.setGeometry(QtCore.QRect(110, 158, 113, 20))
        self.LE_Volume.setObjectName("LE_Volume")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 158, 91, 21))
        self.label_7.setObjectName("label_7")
        self.PB_Ready = QtWidgets.QPushButton(Form)
        self.PB_Ready.setGeometry(QtCore.QRect(10, 200, 81, 31))
        self.PB_Ready.setObjectName("PB_Ready")
        self.PB_Cancel = QtWidgets.QPushButton(Form)
        self.PB_Cancel.setGeometry(QtCore.QRect(140, 200, 81, 31))
        self.PB_Cancel.setObjectName("PB_Cancel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Сорт:"))
        self.label_3.setText(_translate("Form", "Степень обжарки:"))
        self.label_4.setText(_translate("Form", "Вид:"))
        self.label_5.setText(_translate("Form", "Вкус:"))
        self.label_6.setText(_translate("Form", "Цена:"))
        self.label_7.setText(_translate("Form", "Объём:"))
        self.PB_Ready.setText(_translate("Form", "Готово"))
        self.PB_Cancel.setText(_translate("Form", "Отмена"))
